[package]
name = "spectrefs"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
blake3 = { version = "1.5", default-features = false }
zstd-safe = { version = "7.2", default-features = false }
chacha20poly1305 = { workspace = true }
bitflags = { workspace = true }
zerocopy = { workspace = true }
heapless = "0.9"
